### ISSUE TITLE
Installed on my mac, but doesn't work at all ...

### ISSUE THREAD

**Issue by ahmedmusawir** [AvinZarlez/vscode-comment-snippets#8]
No matter how many times I reload, it does nothing. I'm running High Sierra Mac osx ...

**Comment by AvinZarlez** [comment]
None of the snippets appear when you type? Are other snippets working for you? Are there any error messages when the package loads?

I made this at a hackathon a long time ago at this point. I made it work for comments only in c, objective c, c++ and java code. Are you working on a file of that type?

**Comment by ahmedmusawir** [comment]
Thanx for your reply. Yes, snippets from other extensions work fine. And
I'm working on a React project.

**Comment by AvinZarlez** [comment]
Well, as I said, this extension only has comment snippets for c, objective c, c++ and java, so that would be why you don't see anything. React is JavaScript.

Though if you wanted to modify this extension to make it work for JavaScript, it could be easily be done I believe. Depending on what kind of comment Snippets you'd like, might not have to change much at all.
